### ISSUE TITLE
Decimal logical type isn't parsed correctly

### ISSUE THREAD

**Issue by ziggythehamster** [benwatson528/intellij-avro-parquet-plugin#33] opened 2020-06-10 23:42 UTC
This Avro file (in the ZIP) has a very simple schema:

```json
{
  "type" : "record",
  "name" : "person",
  "namespace" : "some-sample",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "age",
    "type" : "int"
  }, {
    "name" : "salary",
    "type" : {
      "type" : "bytes",
      "logicalType" : "decimal",
      "precision" : 9,
      "scale" : 6
    }
  } ]
}
```

Unfortunately, the bytes + decimal logical type isn't parsed and the raw bytes appear:

![image](https://user-images.githubusercontent.com/66674/84329310-43f77d80-ab39-11ea-806b-9fcd9425acf4.png)

Here's the .avro file:

[sample-test.zip](https://github.com/benwatson528/intellij-avro-parquet-plugin/files/4761753/sample-test.zip)

**Comment by benwatson528** [comment] 2020-06-11 07:43
Hello,

This plugin uses `org.apache.avro:avro:1.9.2`, which decodes Avro files according to the latest Avro specification. See [AvroFileReader.java](https://github.com/benwatson528/intellij-avro-parquet-plugin/blob/master/src/main/java/uk/co/hadoopathome/intellij/viewer/fileformat/AvroFileReader.java) for its usage.

The [official Avro docs](https://avro.apache.org/docs/current/spec.html#Logical+Types) say "_Language implementations may choose to represent logical types with an appropriate native type, although this is not required_". I suspect that the decoder sees a field of type `bytes` and decodes it directly into that without taking the logical type into account.

I will take a look this weekend just to make sure that the issue isn't on my end and I'll get back to you.

Ben

**Comment by benwatson528** [comment] 2020-06-11 16:58
Hello,

I've been able to take a quick look this evening, and I can confirm that what is displayed is what is returned from the Avro library.

![image](https://user-images.githubusercontent.com/6214761/84416926-c8ff9700-ac0c-11ea-8da0-5583c2a97294.png)
 
So I'm afraid this is an issue with the Avro library itself and not something that I can control within the plugin.

Ben

**Comment by ziggythehamster** [comment] 2020-06-11 17:30
Your GenericDatumReader instance doesn't have any logical type conversions loaded. This API is weird, here's how I made it work in Scala by adding the logical type conversions to the singleton GenericData instance (which seems wrong to me as a Ruby programmer but maybe this is how they really intend on you doing it):

```scala
import org.apache.avro.Conversions
import org.apache.avro.file.DataFileReader
import org.apache.avro.generic.{ GenericData, GenericDatumReader, GenericRecord }

GenericData.get().addLogicalTypeConversion(new Conversions.DecimalConversion())

val file = new java.io.File("sample-test.avro")
val reader = new GenericDatumReader[GenericRecord]()
val dataFileReader = new DataFileReader[GenericRecord](file, reader)
val record = dataFileReader.next()
```

I think you could create a subclass of `GenericDatumReader` which uses the protected `GenericData` constructor, where you'd create a new instance of `GenericData` that you add the logical type conversion to. I'm not sure why the constructor is protected, though, so maybe it needs some additional care that I'd need to read the code to figure out.

You probably also want to add all of the conversions, since viewing microseconds as longs instead of timestamps is a little funky.

**Comment by benwatson528** [comment] 2020-06-11 18:08
Thanks this is very helpful. Ideally I'd like this all to be taken care of for me (after all I'm reading Avro in the recommended way using the official library), but this doesn't look like too much effort to add support. Will take a look this weekend. Thanks for the sample file, it's very helpful.

Ben

**Comment by ziggythehamster** [comment] 2020-06-11 18:46
I would also rather it did that but I guess the GenericRecord implementation doesn't load logical type converters by default and SpecificRecord does.

FWIW, non-Java implementations typically always handle the logical types (though I know avro for ruby does not yet support Decimal... We're making a patch). I'm not sure what the rationale is behind the default in Java. It's probable it's just poorly documented and there's a more correct way of doing it that I don't know because I'm not steeped in this ecosystem or Java

**Comment by benwatson528** [comment] 2020-06-14 12:12
This is fixed now and should be live on the IntelliJ Marketplace in the next couple of days - I hope you don't mind if I use your sample file for unit tests?

**Closed** 2020-06-14 12:12 UTC

**Comment by ziggythehamster** [comment] 2020-06-15 17:41
No, go for it. Thanks for adding support for this :).

I will point out a potential gotcha though:

https://github.com/benwatson528/intellij-avro-parquet-plugin/pull/36/files#diff-9543657fa3679774cdf2f2cff72fa7d8R15-R24

You've done `GenericData.get()`, which returns a singleton. So you're not really creating a generic data instance so much as you're decorating the singleton. If you made it a void instead and then called `GenericData.get()` instead of using `genericData`, it would have the same effect.

I'm of the opinion that it doesn't really matter - nothing really should care if you've enabled logical type conversions globally. But, the method name is potentially misleading. Maybe you need to go `GenericData.get().clone()`? I have no idea if that will have the intended effect either, though. I'm just barely a Scala programmer, and the languages I use the rest of the time are all non-JVM languages. :)
